import { createElement } from 'lwc';
import FormCreateContact from 'c/formCreateContact';

describe('c-form-create-contact', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-form-create-contact', {
            is: FormCreateContact
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(element.shadowRoot.querySelector('h1').textContent).toBe('Create Contact');
    });
});